MODULE:= $(shell basename $(CURDIR))
INCLUDES = -I./include -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include \
	-I$(RIOTBASE)/sys/net/net_help -I$(RIOTBASE)/sys/net/destiny/include -I$(RIOTBASE)/sys/net/sixlowpan/include

include $(RIOTBASE)/Makefile.base
