MODULE:= $(shell basename $(CURDIR))
INCLUDES = -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include \
	-I$(RIOTBASE)/sys/net/destiny/include -I$(RIOTBASE)/sys/net/sixlowpan/include -I$(RIOTBASE)/sys/net/net_help/ \
	-I./include -I$(OONFBASE)/src-api -I$(RIOTLIBS)

include $(RIOTBASE)/Makefile.base
